// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package ipify

type GetParams struct {
	Format string
}

// GetOkJSONResponse defines a model
type GetOkJSONResponse struct {
	IP string `json:"ip,omitzero"`
}
