// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package ipify

import "net"

type GetParams struct {
	Format string
}

// IPWrapper defines a model
type IPWrapper struct {
	IP net.IP `json:"ip,omitzero"`
}
